# Generated by Django 5.0.9 on 2024-10-24 10:47

import an_najah_organizer.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[an_najah_organizer.users.models.Validator()], verbose_name='username'),
        ),
    ]
