# Generated by Django 5.0.9 on 2024-10-23 16:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomdetails',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='roomdetails',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='roomdetails',
            name='lcd',
        ),
        migrations.RemoveField(
            model_name='roomdetails',
            name='windows',
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.roomitems'),
        ),
    ]
