# Generated by Django 5.0.9 on 2024-10-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roomitems_remove_roomdetails_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_number',
            field=models.CharField(max_length=10),
        ),
    ]
