# Generated by Django 5.0.9 on 2024-10-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_floor_floor_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=set(),
        ),
    ]
